### ISSUE TITLE
Server Save box - Não está considerando timezone

### ISSUE THREAD

**Issue by sircurse** [lucasgiovannibr/myaac#14]
Oi,

Percebi que box de server save ao lado >>> está pegando a hora local do navegador e não está considerando o timezone do servidor.
Por ex, o servidor está com horario local no BR, e eu estou na europa... Em tese o server save deveria ser (agora no momento que estou digitando) dentro de 11 horas, só que ele está mostrando como se o server seve fosse ocorrer daqui 6 horas.

Curse.

**Comment by sircurse** [comment]
Oi Lucas, fiz algumas alterações nesse código do server countdown, espero que seja útil pra vc tb. Nessas alterações resolve o problema do números quando tiverem menos de 2 digitos (visivelmente ficava feio), então agora ele sempre ficará com dois digitos (01, 02, 03...)

Adicionei a variavel do server save e as conversões necessárias, assim não importa de qual país o usuário esteja acessando, sempre vai contar o tempo correto para o server save.

--Curse.

<?php
global $config;
$server_save = $config['server_save'];
$explodeServerSave = explode(':', $server_save);
$hours_ServerSave = $explodeServerSave[0];
$minutes_ServerSave = $explodeServerSave[1];
$seconds_ServerSave = $explodeServerSave[2];
$timezone = $config['date_timezone'];
?>
<script>
	function convertUTCDateToLocalDate(date) {
    date.setMinutes(date.getMinutes() - date.getTimezoneOffset());
    return date;
	};
	
	function convertTZ(date, tzString) {
		return new Date((typeof date === "string" ? new Date(date) : date).toLocaleString("en-US", {timeZone: tzString}));   
	};
	
	var serverSaveTime = new Date("Jan 01, 2050 <?php echo $hours_ServerSave ?>:<?php echo $minutes_ServerSave ?>:<?php echo $seconds_ServerSave ?>");
	var x = setInterval(function() {
		
		var countDownTime = convertUTCDateToLocalDate(new Date(serverSaveTime));
		
		var timeUTC = new Date()
		var localTime = convertUTCDateToLocalDate(new Date(timeUTC));
		var now = convertTZ(localTime, "<?php echo $timezone ?>")
		
		var distance = countDownTime - now;
		var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
		var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
		var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        document.getElementById("timerServerSave").innerHTML = "" + ('0' + hours).substr(-2) + ":" + ('0' + minutes).substr(-2) + ":" + ('0' + seconds).substr(-2) + "";

		if (distance < 0) {
			clearInterval(x);
			document.getElementById("timerServerSave").innerHTML = "Server save now!";
		}
	}, 1000);
</script>

**Comment by flowbomba** [comment]
Eu estava tentando usar seu código mas não funciona, o server save não mostra nenhum número
