### ISSUE TITLE
Is it possible to disable/hide char bazaar through config? 

### ISSUE THREAD

**Issue by lucasgrizante** [lucasgiovannibr/myaac#21]
Is it possible to disable char bazaar through configuration files? (either template or config.local.php)

Best regards

**Comment by slawkens** [comment]
You can simply remove the files responsible for bazaar:

owncharactertrades.php
pastcharactertrades.php
ownbids.php
currentcharactertrades.php
createcharacterauction.php

Hope I didn't miss any ;)
