### ISSUE TITLE
Char bazar dont give champions

### ISSUE THREAD

**Issue by majnero** [lucasgiovannibr/myaac#24]
Script dont gives characters to account win.
Only gives character to account in db id 1 Plese help

**Comment by Berzekz** [comment]
Same problem here @lucasgiovannibr 
Dont give the character for the winner and dont delivery the coins to the seller

**Comment by Berzekz** [comment]
Any change for you fix that @lucasgiovannibr  ? 
I can pay for that !

**Comment by lucasgiovannibr** [comment]
The system is only finalized when the buyer or seller finishes, the button to finalize the sale is only visible from the auction end date.
Remembering that the characters go to the account with id 1 that would be the GOD and once the sale is made it returns to the account that sold it or if you have received an offer there it will be sent to the buyer's account.

**Comment by lucasgiovannibr** [comment]
I do not intend to continue with this project as I am already focused on another.
If you want to follow CanaryAAC.
