### ISSUE TITLE
Last step from Char-bazaar

### ISSUE THREAD

**Issue by Berzekz** [lucasgiovannibr/myaac#4]
createcharacterauction.php(1708): PDO->exec('INSERT INTO `my...')

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '11:56:32, 20220223 11:56:32)' at line 1 

$insert_auction = $db->exec('INSERT INTO `myaac_charbazaar` (`account_old`, `account_new`, `player_id`, `price`, `date_end`, `date_start`) VALUES (' . $account_old .', ' . $account_new .', ' . $player_id .', ' . $price .', ' . $date_end .', ' . $date_start .')');

![image](https://user-images.githubusercontent.com/69734045/155342388-b5ad6090-b8bc-470b-9191-e6f7c26b4b94.png)

**Comment by lucasgiovannibr** [comment]
Did you test with the last published fix? Today I posted one related to this error.

**Comment by Berzekz** [comment]
> Did you test with the last published fix? Today I posted one related to this error.

Yes, can be my MYSQL ? looks like they trying to add the start and end date from auction on database but unsuccessfully

I can show you, if you want. My disc: Berzekz#8739

**Comment by lucasgiovannibr** [comment]
@Berzekz I just posted a fix related to this error.
I had the wrong date format.

**Comment by Berzekz** [comment]
Works like a charm, thanks and nice work ♥
