### ISSUE TITLE
Bid on Bazaar

### ISSUE THREAD

**Issue by Berzekz** [lucasgiovannibr/myaac#5]
When trying to bid a char in the bazaar:

![image](https://user-images.githubusercontent.com/69734045/156014739-9623452f-40d7-4e63-bd20-fad74bf08c9f.png)

**Comment by lucasgiovannibr** [comment]
This error refers to line 1366 of currentcharactertrades.php
Check if there is a coins table in accounts, because this line only checks.

**Comment by Berzekz** [comment]
> This error refers to line 1366 of currentcharactertrades.php Check if there is a coins table in accounts, because this line only checks.

![image](https://user-images.githubusercontent.com/69734045/156043909-6d048d82-45c7-4b3f-8d7e-114676ecc55f.png)

**Comment by lucasgiovannibr** [comment]
Have you tested the last commit? without modifying anything? because I saw that you published a change and it involves precisely the coins.

**Comment by Berzekz** [comment]
Yes tested with all update of this rep and without any change, even with my change this dont affect this functions
https://github.com/lucaslking/myaac/blob/7d79b88224b817534fdec6d93f2ca83df3184b78/system/pages/currentcharactertrades.php#L1367

**Comment by Berzekz** [comment]
closed and the solution ?
