### ISSUE TITLE
Missing Tibia Coins function

### ISSUE THREAD

**Issue by Berzekz** [lucasgiovannibr/myaac#6]
Missing Tibia Coins function at account management page 
Catching PremDays
$account_coins = $account_logged->getPremDays();

https://github.com/lucaslking/myaac/blob/7d79b88224b817534fdec6d93f2ca83df3184b78/system/pages/accountmanagement.php#L76

**Comment by lucasgiovannibr** [comment]
Yes, I will still make an update in this area of functions.
I'm finishing some things with higher priority and so I'll focus on improvements like creating functions.

**Comment by Berzekz** [comment]
What about my PR ?
